# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Buy and Sell your used cell phones, tablets, laptops, and other consumer electronics! We pay more for your device than all major competitors. Check out our website and contact us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: customerservice@platinumwireless.solutions
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Platinum Wireless Solutions, LLC

# API settings
google_api_key:

# Build settings
markdown: kramdown
